// File: <Your Project Root>/build.gradle

buildscript {
    repositories {
        google() // Required for Firebase and Google services
        mavenCentral()
    }
    dependencies {
        // Add the Google services plugin as a dependency
        classpath 'com.google.gms:google-services:4.4.2'  // Latest version
    }
}

allprojects {
    repositories {
        google() // Ensure Firebase dependencies can be fetched
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
